"""
pages/2_About_the_Classifier.py

Information about the LLM Score classifier built into SIEVE.
"""

import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="SIEVE — About the Classifier",
    page_icon="🔬",
    layout="wide",
)

st.title("🤖 About the LLM Score Classifier")
st.caption("P(AI-generated) for every extracted code snippet")
st.divider()

# ── Overview ──────────────────────────────────────────────────────────────────

st.subheader("Overview")
st.markdown("""
SIEVE annotates each extracted code snippet with `llm_score` — a probability
in [0, 1] indicating how likely the snippet is to be AI-generated rather than
human-written.

The classifier is a fine-tuned
[`microsoft/codebert-base`](https://huggingface.co/microsoft/codebert-base)
model with a linear classification head. It was trained on a labeled dataset
of 114,186 code snippets across four programming languages and nine LLMs.

Model weights are publicly available on HuggingFace:
[mrahman2025/sieve-llm-classifier](https://huggingface.co/mrahman2025/sieve-llm-classifier)
""")

st.divider()

# ── Architecture ──────────────────────────────────────────────────────────────

st.subheader("Architecture")
st.markdown("""
```
Code snippet (truncated to 512 tokens)
        ↓
CodeBERT encoder (microsoft/codebert-base, 125M params)
        ↓
[CLS] token embedding (768-dim)
        ↓
Dropout (p=0.1)
        ↓
Linear head (768 → 1)
        ↓
Sigmoid → llm_score ∈ [0, 1]
```

**Training details:**
- Loss: Binary Cross-Entropy with class weighting
- Optimizer: AdamW (lr=2e-5, weight decay=0.01)
- Effective batch size: 32 (gradient accumulation × 2)
- Warmup: 10% of total steps
- Early stopping: patience = 2 epochs on validation loss
- Best checkpoint: epoch 2 (val loss = 0.168)
""")

st.divider()

# ── Training Data ─────────────────────────────────────────────────────────────

st.subheader("Training Data")
st.markdown("114,186 samples — 54,668 human-written · 59,518 AI-generated")

data = {
    "Language":        ["Python", "Java", "JavaScript", "C++"],
    "Human functions": [10000, 10000, 9779, 9051],
    "AI functions":    [10000, 11912, 10187, 9763],
    "Human classes":   [5000, 5000, 838, 5000],
    "AI classes":      [5000, 5832, 976, 5848],
}
df = pd.DataFrame(data)
st.dataframe(df, use_container_width=True, hide_index=True)

st.markdown("""
**Human code** was collected from GitHub repositories created after January 2024
using SIEVE itself, ensuring temporal contamination-freedom.

**AI-generated code** was produced by prompting 9 LLMs with function/class
signatures extracted from the human corpus:

| LLMs for Python | LLMs for Java / JavaScript / C++ |
|---|---|
| Claude 3 Haiku | DeepSeek-V3.1 |
| Claude 4.5 Haiku | Llama 3.3 70B Instruct |
| GPT-3.5 | Llama 4 Maverick 17B |
| GPT-OSS | Mistral Small 24B |
| | GPT-OSS 20B |
""")

st.divider()

# ── Performance ───────────────────────────────────────────────────────────────

st.subheader("Performance")
st.markdown("Evaluated on a held-out test set of 11,419 samples (10% stratified split).")

col1, col2, col3, col4, col5 = st.columns(5)
col1.metric("Accuracy", "94.42%")
col2.metric("F1", "94.78%")
col3.metric("Precision", "92.57%")
col4.metric("Recall", "97.09%")
col5.metric("AUROC", "99.02%")

st.markdown("**Per-language breakdown:**")
perf = {
    "Language":  ["Python", "Java", "JavaScript", "C++"],
    "N":         [3000, 3275, 2177, 2967],
    "Accuracy":  ["94.90%", "94.63%", "94.72%", "93.50%"],
    "F1":        ["94.87%", "95.15%", "95.07%", "94.07%"],
    "AUROC":     ["99.03%", "99.10%", "99.34%", "98.70%"],
}
st.dataframe(pd.DataFrame(perf), use_container_width=True, hide_index=True)

st.info(
    "The classifier leans toward **higher recall** (97.09%) over precision "
    "(92.57%) — it is more likely to flag a human snippet as potentially "
    "AI-generated than to miss an AI-generated one. This is the right "
    "trade-off for a contamination detection tool.",
    icon="ℹ️",
)

st.divider()

# ── Limitations ───────────────────────────────────────────────────────────────

st.subheader("Limitations")
st.markdown("""
- **JavaScript classes** are underrepresented in training (838 human, 976 AI)
  due to the naturally function-heavy nature of the JS corpus.
- The classifier was trained on code generated by specific LLMs as of early 2026.
  Newer models with significantly different generation patterns may reduce accuracy.
- Very short snippets (< 5 tokens) may receive unreliable scores.
- The model processes at most 512 tokens — very long functions are truncated.
""")